name: Docker Multi-Arch Build for GHCR

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker-multiarch:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        config: [release, debug]
        compiler: [gcc, clang]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU for emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image tag
        id: tag
        run: |
          IMAGE_TAG=${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.config }}
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.multiarch
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: ghcr.io/${{ github.repository_owner }}/espeak-ng:${{ steps.tag.outputs.tag }}
          build-args: |
            ARCH=${{ matrix.arch }}
            COMPILER=${{ matrix.compiler }}
            CONFIG=${{ matrix.config }}
