name: fuzzing

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  build:
    uses: ./.github/workflows/workflow-for-fuzzing-build.yml

  fuzzing:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        lang: [af, am, an, ar, as, az, ba, be, bg, bn, bpy, bs, ca, chr, cmn, cs, cv, cy, da, de, el, en, eo, es, et, eu, fa, fi, fo, fr, ga, gd, gn, grc, gu, hak, haw, he, hi, hr, ht, hu, hy, hyw, ia, id, io, is, it, ja, jbo, ka, kaa, kk, kl, kn, ko, kok, ku, ky, la, lb, lfn, lt, ltg, lv, mi, mk, ml, mr, ms, mt, mto, nb, nci, ne, nl, nog, om, or, pa, pap, piqd, pl, pt-BR, py, qdb, qu, quc, qya, ro, ru, ru-LV, sd, shn, sjn, sk, sl, smj, sq, sr, sv, sw, ta, te, th, ti, tk, tn, tr, tt, ug, uk, ur, uz, vi, xex, yue, mb-en1]
    uses: ./.github/workflows/workflow-for-fuzzing.yml
    with:
      lang: ${{ matrix.lang }}
