name: fuzzing

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  build:
    uses: ./.github/workflows/workflow-for-fuzzing-build.yml

  fuzzing:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        lang: [af, am, an, ar, as, az, ba, be, bg, bn, bpy, bs, ca, chr, cmn, cs, cv, cy, da, de, el, en, eo, es, et, eu, fa, fi, fo, fr, ga, gd, gn, grc, gu, hak, haw, he, hi, hr, ht, hu, hy, hyw, ia, id, io, is, it, ja, jbo, ka, kaa, kk, kl, kn, ko, kok, ku, ky, la, lb, lfn, lt, ltg, lv, mi, mk, ml, mr, ms, mt, mto, nb, nci, ne, nl, nog, om, or, pa, pap, piqd, pl, pt-BR, py, qdb, qu, quc, qya, ro, ru, ru-LV, sd, shn, sjn, sk, sl, smj, sq, sr, sv, sw, ta, te, th, ti, tk, tn, tr, tt, ug, uk, ur, uz, vi, xex, yue, en+adam, en+Alex, en+Alicia, en+Andrea, en+Andy, en+anika, en+anikaRobot, en+Annie, en+announcer, en+antonio, en+AnxiousAndy, en+aunty, en+belinda, en+benjamin, en+boris, en+caleb, en+croak, en+david, en+Demonic, en+Denis, en+Diogo, en+ed, en+edward, en+edward2, en+f1, en+f2, en+f3, en+f4, en+f5, en+fast, en+Gene, en+Gene2, en+grandma, en+grandpa, en+gustave, en+Henrique, en+Hugo, en+ian, en+iven, en+iven2, en+iven3, en+iven4, en+Jacky, en+john, en+kaukovalta, en+klatt, en+klatt2, en+klatt3, en+klatt4, en+klatt5, en+klatt6, en+Lee, en+linda, en+m1, en+m2, en+m3, en+m4, en+m5, en+m6, en+m7, en+m8, en+marcelo, en+Marco, en+Mario, en+max, en+Michael, en+michel, en+miguel, en+Mike, en+mike2, en+Nguyen, en+norbert, en+pablo, en+paul, en+pedro, en+quincy, en+Reed, en+RicishayMax, en+RicishayMax2, en+RicishayMax3, en+rob, en+robert, en+robosoft, en+robosoft2, en+robosoft3, en+robosoft4, en+robosoft5, en+robosoft6, en+robosoft7, en+robosoft8, en+sandro, en+shelby, en+steph, en+steph2, en+steph3, en+Storm, en+travis, en+Tweaky, en+UniRobot, en+victor, en+whisper, en+whisperf, en+zac, mb-en1]
    uses: ./.github/workflows/workflow-for-fuzzing.yml
    with:
      lang: ${{ matrix.lang }}
